version: '3'
services:
  goflow:
    #image: 'cloudflare/goflow:latest'
    build: /root/go/src/github.com/demonix/goflow
    ports:
      - '8080:8080'
      - '6343:6343/udp'
      - '29996:2055/udp'
    restart: always
    entrypoint: '/bin/sh'
    command: >
      -c "sleep 15 ;
      /goflow -kafka.brokers kafka:9092
      -kafka.topic flows"