{
 "title": "Traffic Copy",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Instant traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  (cast(extract(epoch from date_inserted) as integer)/30)*30 AS \"time\",\n  sum(bytes*(case when sampling_rate = 0 then 1 else sampling_rate end) *8)/30 as \"traffic\"\nFROM flows\nWHERE\n  $__timeFilter(date_inserted)\nGROUP BY \"time\"\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Top source IPs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT src_ip, count(*), \nsum(bytes*(case when sampling_rate = 0 then 1 else sampling_rate end) ) as sumBytes\nFROM flows\nWHERE\n  $__timeFilter(date_inserted)\n  GROUP BY src_ip\n"
    }
   ]
  },
  {
   "title": "Top source proj",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT src_prj, count(*), sum(bytes*(case when sampling_rate = 0 then 1 else sampling_rate end) ) as sumBytes FROM flows \nWHERE\n  $__timeFilter(date_inserted)\nGROUP BY src_prj"
    }
   ]
  },
  {
   "title": "Top destination IPs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT dst_ip, count(*), sum(bytes*(case when sampling_rate = 0 then 1 else sampling_rate end) ) as sumBytes FROM flows \n   WHERE $__timeFilter(date_inserted)\n  GROUP BY dst_ip"
    }
   ]
  },
  {
   "title": "Top destination proj",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT dst_prj, count(*), sum(bytes*(case when sampling_rate = 0 then 1 else sampling_rate end) ) as sumBytes FROM flows\nWHERE $__timeFilter(date_inserted)\nGROUP BY dst_prj"
    }
   ]
  }
 ]
}